spring.application.name=backend
server.port=${PORT:3002}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/assignment_submission_system?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

app.cors-origin=${CORS_ORIGIN:http://localhost:5173}
app.upload-dir=${UPLOAD_DIR:uploads}
